### ISSUE TITLE
Conflict between features "hashbrown" and "std"

### ISSUE THREAD

**Issue by conr2d** [near/borsh-rs#334]
When writing a crate that depends on `borsh` with the following `Cargo.toml` configuration:

```toml
[dependencies]
borsh = { version = "1.5.4", features = ["hashbrown"] }

[features]
default = ["std"]
std = ["borsh/std"]
```

a compilation error occurs because the features "hashbrown" and "std" cannot be enabled simultaneously. 

Would it be possible to expose standard library hash collections from `__private::maybestd` when both features are enabled?

Currently, there seems to be no way to exclude an unused hashbrown dependency in this case. However, this change would enable writing a package that supports both std and no_std environments without conflict.

**Comment by dj8yfo** [comment]
this would work, wouldn't it? 

```toml 
[dependencies]
borsh = { version = "1.5.4", default-features = false}

[features]
default = ["std"]
hashbrown = ["borsh/hashbrown", "dep:hashbrown"]
std = ["borsh/std"]
```

kind of not cool this propagates up to features of client crate, but then the users of your crate would know where the `HashMap`-s come from, which really is not a `borsh::hash_collections` module . 

`borsh::io` is slightly a different story, because it exposes stuff which is used in `borsh`-s trait signatures, and 
it's kind of obligatory for borsh to provide glue code which allows to write its trait implementations which compile in both std and no_std without much additional effort.
